name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.35.0-jammy
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run your code analysis
        run: flake8 --verbose --statistics --show-source

      - name: Run your tests Chrome
        run: pytest -s -v -r test --junitxml=test-results.xml
        continue-on-error: true

      - name: Run your tests Webkit
        run: pytest -s -v -r test --browser webkit --junitxml=test-results-webkit.xml
        continue-on-error: true

      - name: Upload test results chrome
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: test-results.xml

      - name: Upload test results webkit
        uses: actions/upload-artifact@v3
        with:
          name: Test Results
          path: test-results-webkit.xml

      - name: Surface failing tests chrome
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results.xml
          summary: true
          display-options: fEX
          fail-on-empty: true

      - name: Surface failing tests webkit
        if: always()
        uses: pmeier/pytest-results-action@main
        with:
          path: test-results-webkit.xml
          summary: true
          display-options: fEX
          fail-on-empty: true